### PR TITLE
Don't use alias_method_chain. Fixes #4

### LINKED ISSUE #4: alias_method_chain is deprecated in Rails 5
It's used here: https://github.com/cbeer/deprecation/blob/87d3a4ba5c745318eb18e3ee6ab444a373194ce7/lib/deprecation/method_wrappers.rb#L11

### PR DESCRIPTION
**Pull request by jcoyne**
alias_method_chain is deprecated in Rails 5

### CODE REVIEW

**Comment by cbeer** [comment]
I guess this requires dropping Ruby 1.9 support?

**Comment by jcoyne** [comment]
Yes, I suppose it does.

**Comment by jcoyne** [comment]
@cbeer It appears that `prepend` is private in Ruby 2.0.  Do you want me to handle that or drop 2.0?

**Comment by jcoyne** [comment]
@cbeer ping. What needs to happen here?

**Pull request merged**
